server {
    listen 80;

    # Serve your HTML
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /podcasts/ {
        alias /data/podcasts/;
        # Force the correct header for subtitles
        types {
            text/vtt vtt;
        }
        default_type text/vtt;
    
        # Allow the browser to read this from your web page's origin
        add_header Access-Control-Allow-Origin *;
    }

    # PROXY ICECAST: Now accessible at http://localhost:8080/icecast/
    location /icecast/ {
        # The trailing slash and proxy_pass logic are sensitive
        proxy_pass http://radio-icecast:8000/;
        proxy_set_header Host $host;
    
        # Ensure arguments (the ?nocache part) are passed correctly
        proxy_pass_request_headers on;
    }
}
